### ISSUE TITLE
Question about linking kubridge in GPL-v3 Project

### ISSUE THREAD

**Issue by jackmcellin** [pspdev/kubridge#5]
I have a quick question regarding the license for kubridge. I've modified Retroarch to detect whether it is running on a PSP GO (where it can use internal storage) or a standard PSP (where it needs to use a memory stick).This fixes a bug where the default config can't be loaded if there is no memory stick present. 

I use kuKernelGetModel() to perform this check. Retroarch is build into a single executable, meaning that I statically link this library with Retroarch, which violates the terms of GPL-v2 (see https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic). Retroarch uses a GPL-v3 license which isn't compatible with GPL-v2 unless it's stated as "GPL-v2 or later". 

My question is if the license is "GPL-v2 only" or if it is "GPL-v2 or later", as that would clarify if I can link against this library or not. Thanks!

**Comment by sharkwouter** [comment]
I'm really sorry, we would love to help you out here, but changing a license requires permission from all contributors. Some of the contributors are not in our community Discord or here on Github, so we cannot ask them for permission to change it. This means we cannot change it.

What is possible is to do something similar to what kubridge does in your own code. The system calls themselves are not copyrightable and are not covered by the license if you're not copying the code around it.

**Comment by jackmcellin** [comment]
Thanks for getting back to me! That's no problem at all, I'll look into it again once I get some free time. That's good to know about the system calls though as that should be all I really need to figure out what model I'm running on.
